// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// IssueTag is the predicate function for issuetag builders.
type IssueTag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
