// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"server/ent/issue"
	"server/ent/issuetag"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IssueTagQuery is the builder for querying IssueTag entities.
type IssueTagQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.IssueTag
	// eager-loading edges.
	withAssignedIssues *IssueQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssueTagQuery builder.
func (itq *IssueTagQuery) Where(ps ...predicate.IssueTag) *IssueTagQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit adds a limit step to the query.
func (itq *IssueTagQuery) Limit(limit int) *IssueTagQuery {
	itq.limit = &limit
	return itq
}

// Offset adds an offset step to the query.
func (itq *IssueTagQuery) Offset(offset int) *IssueTagQuery {
	itq.offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *IssueTagQuery) Unique(unique bool) *IssueTagQuery {
	itq.unique = &unique
	return itq
}

// Order adds an order step to the query.
func (itq *IssueTagQuery) Order(o ...OrderFunc) *IssueTagQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// QueryAssignedIssues chains the current query on the "assignedIssues" edge.
func (itq *IssueTagQuery) QueryAssignedIssues() *IssueQuery {
	query := &IssueQuery{config: itq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issuetag.Table, issuetag.FieldID, selector),
			sqlgraph.To(issue.Table, issue.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, issuetag.AssignedIssuesTable, issuetag.AssignedIssuesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IssueTag entity from the query.
// Returns a *NotFoundError when no IssueTag was found.
func (itq *IssueTagQuery) First(ctx context.Context) (*IssueTag, error) {
	nodes, err := itq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issuetag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *IssueTagQuery) FirstX(ctx context.Context) *IssueTag {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IssueTag ID from the query.
// Returns a *NotFoundError when no IssueTag ID was found.
func (itq *IssueTagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issuetag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *IssueTagQuery) FirstIDX(ctx context.Context) int {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IssueTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IssueTag entity is found.
// Returns a *NotFoundError when no IssueTag entities are found.
func (itq *IssueTagQuery) Only(ctx context.Context) (*IssueTag, error) {
	nodes, err := itq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issuetag.Label}
	default:
		return nil, &NotSingularError{issuetag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *IssueTagQuery) OnlyX(ctx context.Context) *IssueTag {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IssueTag ID in the query.
// Returns a *NotSingularError when more than one IssueTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *IssueTagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = &NotSingularError{issuetag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *IssueTagQuery) OnlyIDX(ctx context.Context) int {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IssueTags.
func (itq *IssueTagQuery) All(ctx context.Context) ([]*IssueTag, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return itq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (itq *IssueTagQuery) AllX(ctx context.Context) []*IssueTag {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IssueTag IDs.
func (itq *IssueTagQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := itq.Select(issuetag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *IssueTagQuery) IDsX(ctx context.Context) []int {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *IssueTagQuery) Count(ctx context.Context) (int, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return itq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (itq *IssueTagQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *IssueTagQuery) Exist(ctx context.Context) (bool, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return itq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *IssueTagQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssueTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *IssueTagQuery) Clone() *IssueTagQuery {
	if itq == nil {
		return nil
	}
	return &IssueTagQuery{
		config:             itq.config,
		limit:              itq.limit,
		offset:             itq.offset,
		order:              append([]OrderFunc{}, itq.order...),
		predicates:         append([]predicate.IssueTag{}, itq.predicates...),
		withAssignedIssues: itq.withAssignedIssues.Clone(),
		// clone intermediate query.
		sql:    itq.sql.Clone(),
		path:   itq.path,
		unique: itq.unique,
	}
}

// WithAssignedIssues tells the query-builder to eager-load the nodes that are connected to
// the "assignedIssues" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *IssueTagQuery) WithAssignedIssues(opts ...func(*IssueQuery)) *IssueTagQuery {
	query := &IssueQuery{config: itq.config}
	for _, opt := range opts {
		opt(query)
	}
	itq.withAssignedIssues = query
	return itq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IssueTag.Query().
//		GroupBy(issuetag.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (itq *IssueTagQuery) GroupBy(field string, fields ...string) *IssueTagGroupBy {
	group := &IssueTagGroupBy{config: itq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return itq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.IssueTag.Query().
//		Select(issuetag.FieldName).
//		Scan(ctx, &v)
//
func (itq *IssueTagQuery) Select(fields ...string) *IssueTagSelect {
	itq.fields = append(itq.fields, fields...)
	return &IssueTagSelect{IssueTagQuery: itq}
}

func (itq *IssueTagQuery) prepareQuery(ctx context.Context) error {
	for _, f := range itq.fields {
		if !issuetag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *IssueTagQuery) sqlAll(ctx context.Context) ([]*IssueTag, error) {
	var (
		nodes       = []*IssueTag{}
		_spec       = itq.querySpec()
		loadedTypes = [1]bool{
			itq.withAssignedIssues != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &IssueTag{config: itq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := itq.withAssignedIssues; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*IssueTag, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.AssignedIssues = []*Issue{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*IssueTag)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   issuetag.AssignedIssuesTable,
				Columns: issuetag.AssignedIssuesPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(issuetag.AssignedIssuesPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, itq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "assignedIssues": %w`, err)
		}
		query.Where(issue.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "assignedIssues" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.AssignedIssues = append(nodes[i].Edges.AssignedIssues, n)
			}
		}
	}

	return nodes, nil
}

func (itq *IssueTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	_spec.Node.Columns = itq.fields
	if len(itq.fields) > 0 {
		_spec.Unique = itq.unique != nil && *itq.unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *IssueTagQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := itq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (itq *IssueTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   issuetag.Table,
			Columns: issuetag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: issuetag.FieldID,
			},
		},
		From:   itq.sql,
		Unique: true,
	}
	if unique := itq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := itq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuetag.FieldID)
		for i := range fields {
			if fields[i] != issuetag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *IssueTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(issuetag.Table)
	columns := itq.fields
	if len(columns) == 0 {
		columns = issuetag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.unique != nil && *itq.unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssueTagGroupBy is the group-by builder for IssueTag entities.
type IssueTagGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *IssueTagGroupBy) Aggregate(fns ...AggregateFunc) *IssueTagGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the group-by query and scans the result into the given value.
func (itgb *IssueTagGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := itgb.path(ctx)
	if err != nil {
		return err
	}
	itgb.sql = query
	return itgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (itgb *IssueTagGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := itgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: IssueTagGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (itgb *IssueTagGroupBy) StringsX(ctx context.Context) []string {
	v, err := itgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = itgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (itgb *IssueTagGroupBy) StringX(ctx context.Context) string {
	v, err := itgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: IssueTagGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (itgb *IssueTagGroupBy) IntsX(ctx context.Context) []int {
	v, err := itgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = itgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (itgb *IssueTagGroupBy) IntX(ctx context.Context) int {
	v, err := itgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: IssueTagGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (itgb *IssueTagGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := itgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = itgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (itgb *IssueTagGroupBy) Float64X(ctx context.Context) float64 {
	v, err := itgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: IssueTagGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (itgb *IssueTagGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := itgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *IssueTagGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = itgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (itgb *IssueTagGroupBy) BoolX(ctx context.Context) bool {
	v, err := itgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (itgb *IssueTagGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range itgb.fields {
		if !issuetag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := itgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (itgb *IssueTagGroupBy) sqlQuery() *sql.Selector {
	selector := itgb.sql.Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(itgb.fields)+len(itgb.fns))
		for _, f := range itgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(itgb.fields...)...)
}

// IssueTagSelect is the builder for selecting fields of IssueTag entities.
type IssueTagSelect struct {
	*IssueTagQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (its *IssueTagSelect) Scan(ctx context.Context, v interface{}) error {
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	its.sql = its.IssueTagQuery.sqlQuery(ctx)
	return its.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (its *IssueTagSelect) ScanX(ctx context.Context, v interface{}) {
	if err := its.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Strings(ctx context.Context) ([]string, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: IssueTagSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (its *IssueTagSelect) StringsX(ctx context.Context) []string {
	v, err := its.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = its.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (its *IssueTagSelect) StringX(ctx context.Context) string {
	v, err := its.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Ints(ctx context.Context) ([]int, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: IssueTagSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (its *IssueTagSelect) IntsX(ctx context.Context) []int {
	v, err := its.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = its.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (its *IssueTagSelect) IntX(ctx context.Context) int {
	v, err := its.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: IssueTagSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (its *IssueTagSelect) Float64sX(ctx context.Context) []float64 {
	v, err := its.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = its.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (its *IssueTagSelect) Float64X(ctx context.Context) float64 {
	v, err := its.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: IssueTagSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (its *IssueTagSelect) BoolsX(ctx context.Context) []bool {
	v, err := its.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (its *IssueTagSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = its.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{issuetag.Label}
	default:
		err = fmt.Errorf("ent: IssueTagSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (its *IssueTagSelect) BoolX(ctx context.Context) bool {
	v, err := its.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (its *IssueTagSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := its.sql.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
