// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/ent/issuetag"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// IssueTag is the model entity for the IssueTag schema.
type IssueTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IssueTagQuery when eager-loading is set.
	Edges IssueTagEdges `json:"edges"`
}

// IssueTagEdges holds the relations/edges for other nodes in the graph.
type IssueTagEdges struct {
	// AssignedIssues holds the value of the assignedIssues edge.
	AssignedIssues []*Issue `json:"assignedIssues,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AssignedIssuesOrErr returns the AssignedIssues value or an error if the edge
// was not loaded in eager-loading.
func (e IssueTagEdges) AssignedIssuesOrErr() ([]*Issue, error) {
	if e.loadedTypes[0] {
		return e.AssignedIssues, nil
	}
	return nil, &NotLoadedError{edge: "assignedIssues"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IssueTag) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case issuetag.FieldID:
			values[i] = new(sql.NullInt64)
		case issuetag.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type IssueTag", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IssueTag fields.
func (it *IssueTag) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case issuetag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			it.ID = int(value.Int64)
		case issuetag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				it.Name = value.String
			}
		}
	}
	return nil
}

// QueryAssignedIssues queries the "assignedIssues" edge of the IssueTag entity.
func (it *IssueTag) QueryAssignedIssues() *IssueQuery {
	return (&IssueTagClient{config: it.config}).QueryAssignedIssues(it)
}

// Update returns a builder for updating this IssueTag.
// Note that you need to call IssueTag.Unwrap() before calling this method if this IssueTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (it *IssueTag) Update() *IssueTagUpdateOne {
	return (&IssueTagClient{config: it.config}).UpdateOne(it)
}

// Unwrap unwraps the IssueTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (it *IssueTag) Unwrap() *IssueTag {
	tx, ok := it.config.driver.(*txDriver)
	if !ok {
		panic("ent: IssueTag is not a transactional entity")
	}
	it.config.driver = tx.drv
	return it
}

// String implements the fmt.Stringer.
func (it *IssueTag) String() string {
	var builder strings.Builder
	builder.WriteString("IssueTag(")
	builder.WriteString(fmt.Sprintf("id=%v", it.ID))
	builder.WriteString(", name=")
	builder.WriteString(it.Name)
	builder.WriteByte(')')
	return builder.String()
}

// IssueTags is a parsable slice of IssueTag.
type IssueTags []*IssueTag

func (it IssueTags) config(cfg config) {
	for _i := range it {
		it[_i].config = cfg
	}
}
