// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/issue"
	"server/ent/issuetag"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IssueTagCreate is the builder for creating a IssueTag entity.
type IssueTagCreate struct {
	config
	mutation *IssueTagMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (itc *IssueTagCreate) SetName(s string) *IssueTagCreate {
	itc.mutation.SetName(s)
	return itc
}

// AddAssignedIssueIDs adds the "assignedIssues" edge to the Issue entity by IDs.
func (itc *IssueTagCreate) AddAssignedIssueIDs(ids ...int) *IssueTagCreate {
	itc.mutation.AddAssignedIssueIDs(ids...)
	return itc
}

// AddAssignedIssues adds the "assignedIssues" edges to the Issue entity.
func (itc *IssueTagCreate) AddAssignedIssues(i ...*Issue) *IssueTagCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return itc.AddAssignedIssueIDs(ids...)
}

// Mutation returns the IssueTagMutation object of the builder.
func (itc *IssueTagCreate) Mutation() *IssueTagMutation {
	return itc.mutation
}

// Save creates the IssueTag in the database.
func (itc *IssueTagCreate) Save(ctx context.Context) (*IssueTag, error) {
	var (
		err  error
		node *IssueTag
	)
	if len(itc.hooks) == 0 {
		if err = itc.check(); err != nil {
			return nil, err
		}
		node, err = itc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IssueTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = itc.check(); err != nil {
				return nil, err
			}
			itc.mutation = mutation
			if node, err = itc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(itc.hooks) - 1; i >= 0; i-- {
			if itc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = itc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, itc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (itc *IssueTagCreate) SaveX(ctx context.Context) *IssueTag {
	v, err := itc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itc *IssueTagCreate) Exec(ctx context.Context) error {
	_, err := itc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itc *IssueTagCreate) ExecX(ctx context.Context) {
	if err := itc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itc *IssueTagCreate) check() error {
	if _, ok := itc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IssueTag.name"`)}
	}
	if v, ok := itc.mutation.Name(); ok {
		if err := issuetag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IssueTag.name": %w`, err)}
		}
	}
	return nil
}

func (itc *IssueTagCreate) sqlSave(ctx context.Context) (*IssueTag, error) {
	_node, _spec := itc.createSpec()
	if err := sqlgraph.CreateNode(ctx, itc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (itc *IssueTagCreate) createSpec() (*IssueTag, *sqlgraph.CreateSpec) {
	var (
		_node = &IssueTag{config: itc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: issuetag.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: issuetag.FieldID,
			},
		}
	)
	if value, ok := itc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: issuetag.FieldName,
		})
		_node.Name = value
	}
	if nodes := itc.mutation.AssignedIssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IssueTagCreateBulk is the builder for creating many IssueTag entities in bulk.
type IssueTagCreateBulk struct {
	config
	builders []*IssueTagCreate
}

// Save creates the IssueTag entities in the database.
func (itcb *IssueTagCreateBulk) Save(ctx context.Context) ([]*IssueTag, error) {
	specs := make([]*sqlgraph.CreateSpec, len(itcb.builders))
	nodes := make([]*IssueTag, len(itcb.builders))
	mutators := make([]Mutator, len(itcb.builders))
	for i := range itcb.builders {
		func(i int, root context.Context) {
			builder := itcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IssueTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, itcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, itcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, itcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (itcb *IssueTagCreateBulk) SaveX(ctx context.Context) []*IssueTag {
	v, err := itcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itcb *IssueTagCreateBulk) Exec(ctx context.Context) error {
	_, err := itcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itcb *IssueTagCreateBulk) ExecX(ctx context.Context) {
	if err := itcb.Exec(ctx); err != nil {
		panic(err)
	}
}
