// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/issue"
	"server/ent/issuetag"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IssueTagUpdate is the builder for updating IssueTag entities.
type IssueTagUpdate struct {
	config
	hooks    []Hook
	mutation *IssueTagMutation
}

// Where appends a list predicates to the IssueTagUpdate builder.
func (itu *IssueTagUpdate) Where(ps ...predicate.IssueTag) *IssueTagUpdate {
	itu.mutation.Where(ps...)
	return itu
}

// SetName sets the "name" field.
func (itu *IssueTagUpdate) SetName(s string) *IssueTagUpdate {
	itu.mutation.SetName(s)
	return itu
}

// AddAssignedIssueIDs adds the "assignedIssues" edge to the Issue entity by IDs.
func (itu *IssueTagUpdate) AddAssignedIssueIDs(ids ...int) *IssueTagUpdate {
	itu.mutation.AddAssignedIssueIDs(ids...)
	return itu
}

// AddAssignedIssues adds the "assignedIssues" edges to the Issue entity.
func (itu *IssueTagUpdate) AddAssignedIssues(i ...*Issue) *IssueTagUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return itu.AddAssignedIssueIDs(ids...)
}

// Mutation returns the IssueTagMutation object of the builder.
func (itu *IssueTagUpdate) Mutation() *IssueTagMutation {
	return itu.mutation
}

// ClearAssignedIssues clears all "assignedIssues" edges to the Issue entity.
func (itu *IssueTagUpdate) ClearAssignedIssues() *IssueTagUpdate {
	itu.mutation.ClearAssignedIssues()
	return itu
}

// RemoveAssignedIssueIDs removes the "assignedIssues" edge to Issue entities by IDs.
func (itu *IssueTagUpdate) RemoveAssignedIssueIDs(ids ...int) *IssueTagUpdate {
	itu.mutation.RemoveAssignedIssueIDs(ids...)
	return itu
}

// RemoveAssignedIssues removes "assignedIssues" edges to Issue entities.
func (itu *IssueTagUpdate) RemoveAssignedIssues(i ...*Issue) *IssueTagUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return itu.RemoveAssignedIssueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (itu *IssueTagUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(itu.hooks) == 0 {
		if err = itu.check(); err != nil {
			return 0, err
		}
		affected, err = itu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IssueTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = itu.check(); err != nil {
				return 0, err
			}
			itu.mutation = mutation
			affected, err = itu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(itu.hooks) - 1; i >= 0; i-- {
			if itu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = itu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, itu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (itu *IssueTagUpdate) SaveX(ctx context.Context) int {
	affected, err := itu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (itu *IssueTagUpdate) Exec(ctx context.Context) error {
	_, err := itu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itu *IssueTagUpdate) ExecX(ctx context.Context) {
	if err := itu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itu *IssueTagUpdate) check() error {
	if v, ok := itu.mutation.Name(); ok {
		if err := issuetag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IssueTag.name": %w`, err)}
		}
	}
	return nil
}

func (itu *IssueTagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   issuetag.Table,
			Columns: issuetag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: issuetag.FieldID,
			},
		},
	}
	if ps := itu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := itu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: issuetag.FieldName,
		})
	}
	if itu.mutation.AssignedIssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := itu.mutation.RemovedAssignedIssuesIDs(); len(nodes) > 0 && !itu.mutation.AssignedIssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := itu.mutation.AssignedIssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, itu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// IssueTagUpdateOne is the builder for updating a single IssueTag entity.
type IssueTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IssueTagMutation
}

// SetName sets the "name" field.
func (ituo *IssueTagUpdateOne) SetName(s string) *IssueTagUpdateOne {
	ituo.mutation.SetName(s)
	return ituo
}

// AddAssignedIssueIDs adds the "assignedIssues" edge to the Issue entity by IDs.
func (ituo *IssueTagUpdateOne) AddAssignedIssueIDs(ids ...int) *IssueTagUpdateOne {
	ituo.mutation.AddAssignedIssueIDs(ids...)
	return ituo
}

// AddAssignedIssues adds the "assignedIssues" edges to the Issue entity.
func (ituo *IssueTagUpdateOne) AddAssignedIssues(i ...*Issue) *IssueTagUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ituo.AddAssignedIssueIDs(ids...)
}

// Mutation returns the IssueTagMutation object of the builder.
func (ituo *IssueTagUpdateOne) Mutation() *IssueTagMutation {
	return ituo.mutation
}

// ClearAssignedIssues clears all "assignedIssues" edges to the Issue entity.
func (ituo *IssueTagUpdateOne) ClearAssignedIssues() *IssueTagUpdateOne {
	ituo.mutation.ClearAssignedIssues()
	return ituo
}

// RemoveAssignedIssueIDs removes the "assignedIssues" edge to Issue entities by IDs.
func (ituo *IssueTagUpdateOne) RemoveAssignedIssueIDs(ids ...int) *IssueTagUpdateOne {
	ituo.mutation.RemoveAssignedIssueIDs(ids...)
	return ituo
}

// RemoveAssignedIssues removes "assignedIssues" edges to Issue entities.
func (ituo *IssueTagUpdateOne) RemoveAssignedIssues(i ...*Issue) *IssueTagUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ituo.RemoveAssignedIssueIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ituo *IssueTagUpdateOne) Select(field string, fields ...string) *IssueTagUpdateOne {
	ituo.fields = append([]string{field}, fields...)
	return ituo
}

// Save executes the query and returns the updated IssueTag entity.
func (ituo *IssueTagUpdateOne) Save(ctx context.Context) (*IssueTag, error) {
	var (
		err  error
		node *IssueTag
	)
	if len(ituo.hooks) == 0 {
		if err = ituo.check(); err != nil {
			return nil, err
		}
		node, err = ituo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IssueTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ituo.check(); err != nil {
				return nil, err
			}
			ituo.mutation = mutation
			node, err = ituo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ituo.hooks) - 1; i >= 0; i-- {
			if ituo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ituo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ituo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ituo *IssueTagUpdateOne) SaveX(ctx context.Context) *IssueTag {
	node, err := ituo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ituo *IssueTagUpdateOne) Exec(ctx context.Context) error {
	_, err := ituo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ituo *IssueTagUpdateOne) ExecX(ctx context.Context) {
	if err := ituo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ituo *IssueTagUpdateOne) check() error {
	if v, ok := ituo.mutation.Name(); ok {
		if err := issuetag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IssueTag.name": %w`, err)}
		}
	}
	return nil
}

func (ituo *IssueTagUpdateOne) sqlSave(ctx context.Context) (_node *IssueTag, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   issuetag.Table,
			Columns: issuetag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: issuetag.FieldID,
			},
		},
	}
	id, ok := ituo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IssueTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ituo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuetag.FieldID)
		for _, f := range fields {
			if !issuetag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != issuetag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ituo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ituo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: issuetag.FieldName,
		})
	}
	if ituo.mutation.AssignedIssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ituo.mutation.RemovedAssignedIssuesIDs(); len(nodes) > 0 && !ituo.mutation.AssignedIssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ituo.mutation.AssignedIssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issuetag.AssignedIssuesTable,
			Columns: issuetag.AssignedIssuesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: issue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IssueTag{config: ituo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ituo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
